// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateRunRecordController from "./create_run_record_controller"
application.register("create-run-record", CreateRunRecordController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadMapPathController from "./load_map_path_controller"
application.register("load-map-path", LoadMapPathController)

import RunTimerController from "./run_timer_controller"
application.register("run-timer", RunTimerController)
